# Generated by Django 3.2.9 on 2022-01-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleprojectpaymentpolicygroupdetailvalue',
            old_name='payment_value_master_unit_id',
            new_name='detail_value_payment_master_unit',
        ),
        migrations.RenameField(
            model_name='saleprojectpaymentpolicygroupdetailvalue',
            old_name='payment_method',
            new_name='detail_value_payment_method',
        ),
        migrations.RenameField(
            model_name='saleprojectpaymentpolicygroupdetailvalue',
            old_name='progressive_percent',
            new_name='detail_value_payment_progressive_percent',
        ),
        migrations.RenameField(
            model_name='saleprojectpaymentpolicygroupdetailvalue',
            old_name='payment_value',
            new_name='detail_value_payment_value',
        ),
    ]
