# Generated by Django 3.2.9 on 2022-01-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20220117_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleprojectpaymentpolicydetailvaluefile',
            name='file_type',
            field=models.IntegerField(blank=True, db_column='file_type', null=True, verbose_name='File Type'),
        ),
    ]
