# Generated by Django 3.2.9 on 2022-01-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_saleprojectpaymentpolicydetailvaluefile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleprojectpaymentpolicydetailvaluefile',
            name='file_type',
            field=models.IntegerField(db_column='file_type', verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='saleprojectpaymentpolicygroupdetailvaluefile',
            name='file_type',
            field=models.IntegerField(blank=True, db_column='file_type', null=True, verbose_name='File Type'),
        ),
    ]
